- src/controllers/LoginController.ts
- src/controllers/OrganizationsController.ts
- src/controllers/UsersController.ts
- src/core/Server.ts
- src/entities/BasicPlugin.ts
- src/entities/GlobalPlugin.ts
- src/entities/Organization.ts
- src/entities/OrganizationLog.ts
- src/entities/RenderJob.ts
- src/entities/RenderJobLog.ts
- src/entities/RenderTask.ts
- src/entities/RenderTaskAttempt.ts
- src/entities/RenderTaskAttemptLog.ts
- src/entities/Role.ts
- src/entities/Slave.ts
- src/entities/User.ts
- src/interfaces/OutUser.ts
- src/validators/OrganizationRequestValidator.ts
- src/validators/UserRequestValidator.ts
* Added OrganizationRequestValidator  
Supported endpoints:
- __[GET]__ ___/organizations___
- __[POST]__ ___/organizations___
- __[GET]__ ___/organizations/:organization_id___
- __[DELETE]__ ___/organizations/:organization_id__
> Added Organization Controller.

- src/controllers/UsersController.ts
- src/entities/BasicPlugin.ts
- src/entities/Organization.ts
- src/entities/OrganizationLog.ts
- src/entities/RenderJob.ts
- src/entities/RenderJobLog.ts
- src/entities/RenderTask.ts
- src/entities/RenderTaskAttempt.ts
- src/entities/RenderTaskAttemptLog.ts
- src/entities/Role.ts
- src/entities/Slave.ts
- src/entities/User.ts
- src/entities/UserToken.ts
- src/errors/RequestError.ts
- src/validators/UserRequestValidators.ts
> Changed cors credentials policy to true

- .idea/inspectionProfiles/Project_Default.xml
- src/controllers/UsersController.ts
- src/core/Server.ts
- src/validators/UserRequestValidators.ts
UsersController routes:
* Route __[GET]__ ___/users___ - get information about all users in the system.
* Route __[POST]__ ___/users___ - register new user.
* Route __[GET]__ ___/users/:user_id___ - get information about user by id.
* Route __[POST]__ ___/users/:user_id___ - edit user information.
* Route __[DELETE]__ ___/users/:user_id___ - delete user.
* Route __[GET]__ ___/users/:user_id/organizations___ - get information about all user organizations.
> Finished user controller.

- src/controllers/OrganizationsController.ts
> [OrganizationsController] Fixed logic for adding/deleting users.

- src/controllers/OrganizationsController.ts
- src/controllers/UsersController.ts
- src/validators/OrganizationRequestValidators.ts
- src/validators/UserRequestValidators.ts
Closes #71 
Routes:
* Route __[GET]__ ___/organizations/:organization_id/availableUsers___ - get users that are not in organization. Query: username: string
> Added GET /organizations/:organization_id/availableUsers - get users that are not in organization

- package.json
- src/controllers/LoginController.test.ts
- src/controllers/RolesController.ts
- src/core/Server.ts
- src/index.ts
> [Server] Added server.close() method.

- package.json
- src/controllers/LoginController.test.ts
- src/core/Server.ts
- src/index.ts
- yarn.lock
> Reworked Server to implement Singleton pattern

- src/controllers/OrganizationsController.ts
Closes #84 
Routes:
- Added:
* __[GET]__ ___/organizations/:organization_id/users/:user_id___
- Edited:
* __[GET]__ ___/organizations/:organization_id/users___
> (#84) organization user

- package.json
- src/core/Authenticator.ts
- src/core/Server.ts
- src/globals.ts
- src/index.ts
- yarn.lock
Moved ___JWT keys___ from __local storage__ for each node to __Redis__ storage. If on startup key is not defined in __Redis__ - it will be generated and added to __Redis__.
- __[Server]__ (closes #117) _Changed server start scenario._
- __[Authenticator]__ (closes #117) _Added key sync mechanism._
> Move jwt key to redis

- src/controllers/LoginController.ts
- src/controllers/UsersController.ts
- src/core/Authenticator.ts
- src/core/Server.ts
- src/index.ts
Reworked Authenticator.
- __[Server]__ (closes #119) _Added middleware that taking key from Redis and putting into ctx.state._
- __[Authenticator, Server]__ (closes #119) _Replaced init() to Server init._
- __[UsersController]__ _Added await to wait for async function createJwt (bearer field in OutUser)._
> Fix incorrect jwt key sync

- src/controllers/VersionsController.ts
- src/core/Authenticator.ts
- src/index.ts
Added /version route.
- __[VersionsController]__  _Added new controller._
- __[Authenticator]__ _Excluded /version from auth routes._
> Add version route

- .github/workflows/deploy-atlas-core-to-gcloud.yml
- package.json
- src/controllers/VersionsController.ts
Raised application version to __0.1.0
- __[GLOBAl]__ _Raised version to __0.1.0__._
This version update for Kubernetes deployment check.
> [Global] Raised app version to 1.0.1

- src/controllers/RolesController.ts
Added logs to get all roles controller.
- __[RolesController]__ _ Added console logs to getRoles() function._
This pull request created to fix incorrect Kubernetes deployment.
> [RolesController] Added console logs to getRoles() function.

- src/core/Authenticator.ts
- src/core/Server.ts
Added __secret loader__ for ___koa-jwt___ middleware.
- __[Authenticator]__ (closes #119) _Added secret loader for koa-jwt middleware._
- __[Server]__ (closes #119) _Removed legacy ```ctx.state.secret``` middleware._
> [Authenticator] (closes #119) Added secretLoader for koa-jwt middleware.

- .github/workflows/deploy-atlas-core-to-gcloud.yml
- src/controllers/OrganizationsController.ts
- src/controllers/RolesController.ts
- src/entities/Role.ts
- src/middlewares/organizationRequestMiddlewares.ts
- src/middlewares/withRoleAccessMiddleware.ts
- src/validators/OrganizationRequestValidators.ts
Added some new middlewares.
- __[withRoleAccessMiddleware]__ (closes #95) _Added new middleware factory to use in controller's routes._
- __[RolesController]__ (closes #95) _Added functionality to store role's swithers._
- __[RolesController]__ (closes #95) _Reworked controller to use new middlewares._
- __[OrganizationsController]__ (closes #95) _Reworked controller to use new middlewares._
New middleware factory provides simple interface to use any roles. Needs to put current __organization__ with _ownerUser_ relation to __ctx.state.organization__. Newly added __findOneOrganizationByRequestParams__ doing this by taking id from request params.  
All this changes needs to be debugged with UI, because it's hardly doable with REST requests.
> (#95) add roles switchers

- src/controllers/UsersController.ts
Changed editUser().
- __[UsersController]__  _Will now work when full user data provided._
> [UsersController] Changed editUser() to work with full user data.

- src/entities/RenderTask.ts
Changed jobId to be notnull
- __[RenderTask entity]__ (closes #109) _Now when creating instance of this entity, it will throw QueryFailedError exception if job column is not set._
> [RenderTask entity] Changed jobId to be notnull.

- src/entities/Role.ts
Changed organization column to be notnull and onDelete CASCADE
- __[Role entity]__ _Changed organization column to be notnull._
> [Role entity] Changed organization column to be notnull.

- src/entities/Organization.ts
Changed ownerUser relation on Organization entity to be ManyToOne
- __[Organization entity]__  _Changed ownerUser relation to be ManyToOne._
> [Organization entity] Changed ownerUser relation to be ManyToOne.

- src/core/Server.ts
Changed cors settings.
- __[Server]__ _Changed __CORS__ settings._
> [Server] Changed cors settings.

- src/controllers/LoginController.ts
Now when user not exist, throwing 404, and if password incorrect - 401.
- __[LoginController]__ _Changed logic._
> [LoginController] Changed logic.

- src/controllers/PluginController.ts
- src/core/Server.ts
Added __CORS__ setup.
- __[Server]__ (closes #..) _Cors setup._
> [CORS] Added origin and accepted headers.

- src/controllers/UploadController.ts
- src/entities/Temp.ts
Added files limit per user. Added files size limit.
- __[UploadController]__  _Added limit per user and file size limit.._
> Add restrictions to upload controller.

- src/controllers/OrganizationsController.ts
- src/controllers/UsersController.ts
- yarn.lock
_Changed all ctx.throw on RequestError_
- __[GLOBAL]__ (closes #47) _Changed all ctx.throw on RequestError._
> [GLOBAL] (#47) Changed all ctx.throw on RequestError.

- src/controllers/JobController.ts
- src/entities/BasicPlugin.ts
- src/entities/Organization.ts
- src/entities/OrganizationLog.ts
- src/entities/Plugin.ts
- src/entities/RenderJob.ts
- src/entities/RenderJobLog.ts
- src/entities/RenderTask.ts
- src/entities/RenderTaskAttempt.ts
- src/entities/RenderTaskAttemptLog.ts
- src/entities/Role.ts
- src/entities/Slave.ts
- src/entities/SystemLog.ts
- src/entities/Temp.ts
- src/entities/User.ts
- src/entities/UserToken.ts
Added JSDoc.
- __[Entities]__ (closes #174) _Added JSDocs for all entities._
> Add jsdoc to entities

- src/controllers/PluginController.ts
Added echanism for getting one plugin details.
- __[PluginController]__ _Added new route._
> [PluginController] Added get plugin route.

- .idea/inspectionProfiles/Project_Default.xml
- package.json
- src/controllers/OrganizationsController.ts
- src/controllers/UploadController.ts
- src/controllers/UsersController.ts
- src/controllers/VersionsController.ts
Fixed error codes, returned on error.
- __[Controllers]__ _Changed error codes._
> Fixed error codes, returned on error.

- src/controllers/JobController.ts
- src/processors/TaskReportsProcessor.ts
Added sorting to get jobs. Also added mechanism to get just one job preview.
- __[JobController]__ _Added sorting._
> [JobController] Added DESC sorting by creation time. Added query params.

- src/core/Server.ts
Added DELETE method to be parsed in koa-body.
- __[Server]__ _Added DELETE method to be parsed in koa-body._
> [Server] Added DELETE method to be parsed in koa-body.

- src/subscribers/RenderJobSubscriber.ts
- src/subscribers/RenderTaskAttemptLogSubscriber.ts
- src/subscribers/RenderTaskAttemptSubscriber.ts
- src/subscribers/RenderTaskSubscriber.ts
[Subscribers] Added logs on error.
Fixed RenderTaskAttemptLog not sending afterUpdate event.
- __[Subscribers]__ _Added logs on error._
- __[RenderTaskAttempt]__ _Added EventSubscriber decorator._
- __[RenderTaskAttemptLog]__ _Added attemptId and taskId to event payload._
> Fixed RenderTaskAttemptLog not sending afterUpdate event.

- src/controllers/OrganizationsController.ts
Fixed user deletion from organization.
- __[OrganizationsController]__ (closes #216) _Added relation for roles when selecting._
> Fixed user deletion from organization.

- src/controllers/RolesController.ts
- src/validators/OrganizationRequestValidators.ts
[RolesController] Reworked POST /:role_id logic.
- __[RolesController]__ _Reworked POST /:role_id logic._
> [RolesController] Reworked POST /:role_id logic.

- src/controllers/OrganizationsController.ts
- src/interfaces/UserWithPermissions.ts
Added route for getting user permissions.
- __[OrganizationController]__ (closes #222) _Added route for getting user permissions._
- __[Interfaces]__ _Added UserWithPermissions interface._
> [OrganizationController] Added route for getting user permissions.

- src/controllers/OrganizationsController.ts
- src/validators/OrganizationRequestValidators.ts
Added ability to add default role on organization creation.
- __[OrganizationsController]__ _Added defaultRole creation._
- __[OrganizationRequestValidator]__ _Added defaultRole._
> [OrganizationsController] Added defaultRole creation.

- src/controllers/OrganizationsController.ts
Edited roles checking in Orgs controller.
- __[OrganizationsController]__ _Edited roles checking._
> [OrganizationsController] Edited roles checking.

- src/controllers/OrganizationsController.ts
Default role will now apply whn creating organization with users.
- __[OrganizationsController]__ (closes #227 ) _Edited addUserToOrg so default role will now apply whn creating organization with users._
> Fix defaultRole not applying when creating org with userIds.

- src/controllers/JobController.ts
- src/controllers/UsersController.ts
- src/validators/UserRequestValidators.ts
Removed password checking for user-editing.
- __[UsersController]__ _Removed password checking for user-editing._
> [UsersController] Removed password checking for user-editing.

- src/processors/TaskReportsProcessor.ts
- src/subscribers/RenderTaskSubscriber.ts
Changed logic for setting tasks status in job.
- __[RenderTaskSubscriber]__ _Changed logic for setting tasks status in job._
- __[TaskReportsProcessor]__ _Added renderTask status setting._
> [RenderTaskSubscriber] Changed logic for setting tasks status in job.

- Dockerfile
- kubernetes/NameSpace.yaml
- kubernetes/Services.yaml
- kubernetes/deployment.yaml
Deploy to new kubernetes.
Added .yaml files.
> [Kubernetes] Deploy to new kubernetes.

- .github/workflows/docker-image-publish.yml
Removed comments from CI
- __[CI]__ (closes #253) _Removed comments from CI._
> Removed comments from CI

- src/entities/typeorm/Organization.ts
- src/entities/typeorm/Slave.ts
Changed organization-slave relation to OneToMany.
- __[entities]__ (closes #200) _Changed relation to OneToMany._
> Changed organization-slave relation to OneToMany.

- .github/workflows/docker-image-publish.yml
- .versionrc.json
- CHANGELOG.md
- Dockerfile
- package.json
- src/controllers/VersionsController.ts
- yarn.lock
New version controller takes version from __package.json__. Also, added config for auto version manager to bump version easier.
- __[Dockerfile]__ _Optimized packages installation._
- __[VersionController]__ _Now version is taken from __package__ file._
- __[standard-version]__ _Added library._
> Created version incrementor

- .dockerignore
- Dockerfile
- __[YourModule]__ (closes #..) _Description._
- __[YourModule]__ (closes #..) _Description._
> fix Dockerfile file

- src/controllers/OrganizationsController.ts
- src/middlewares/organizationRequestMiddlewares.ts
- src/middlewares/withRoleAccessMiddleware.ts
- src/utils/organizations/getUserPermissionLevelById.ts
- __[withRoleAccessMiddleware]__ _Fixed role id checking._
- __[OrganizationsController]__  _Added route for getting user permissionLevel._
- _minor changes_.
> Fix withRoleAccessMiddleware.
